AC_DEFUN([LDISKFS_AC_COMPAT_LB_LINUX_VERSION], [
	linux25="yes"
	AC_SUBST(linux25)

	KMODEXT=".ko"
	AC_SUBST(KMODEXT)

	MODULE_TARGET="M"
	AC_SUBST(MODULE_TARGET)

])

AC_DEFUN([LDISKFS_AC_COMPAT_LB_LINUX_RELEASE], [
	LINUXRELEASE=${LINUX_VERSION}
	AC_SUBST(LINUXRELEASE)

	modulefsdir="/lib/modules/$LINUXRELEASE/updates/kernel/fs/\$(PACKAGE)"
	AC_SUBST(modulefsdir)
])

AC_DEFUN([LDISKFS_AC_COMPAT_LB_LINUX_SYMVERFILE], [
	SYMVERFILE=${LINUX_SYMBOLS}
	AC_SUBST(SYMVERFILE)
])

AC_DEFUN([LDISKFS_AC_COMPAT_LB_LINUX_PATH], [
	LDISKFS_AC_COMPAT_LB_LINUX_VERSION
	LDISKFS_AC_COMPAT_LB_LINUX_RELEASE
	LDISKFS_AC_COMPAT_LB_LINUX_SYMVERFILE
])

AC_DEFUN([LDISKFS_AC_COMPAT_LB_HAVE_EXT4_ENABLED], [
	BACKFSU=${BACKFS/ext/EXT}
	AC_SUBST(BACKFSU) dnl # We need an uppercase version
])
